language: node_js
node_js:
  - 10
addons:
  postgresql: "9.6"
services:
  - docker
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - ~/.cache
before_install:
  - pwd
  - ls
  - curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash
  #- npm install --global hasura-cli
  - rvm install 2.6.5
  - docker run -d -p 8081:8081 -v /home/travis/build/pdbradley/rails-hasura-cypress/hasura/metadata:/hasura-metadata -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@localhost:5432/sandbox_test hasura/graphql-engine:v1.3.1.cli-migrations-v2
  - bash bin/wait_for_port 8081
  - cd hasura/test
  - hasura metadata apply
  - cd ../..
  - gem install bundler
  - bundle install
# install:
  - yarn add cypress
before_script:
  - psql -c 'create database sandbox_test;' -U postgres
  - bin/rails server &
  - bundle exec rake assets:precompile
  # - sleep 10
  - RAILS_ENV=test bundle exec rake db:schema:load
  # - RAILS_ENV=test bundle exec rake your_seed
script:
  # - $(yarn bin)/cypress run --record
  - CYPRESS_RAILS_CYPRESS_OPTS='--record --key bd102e85-84bc-4950-94df-35548710c7a9' rake cypress:run
  - bundle exec rspec spec/models

