language: node_js
node_js:
  - 10
addons:
  postgresql: "9.6"
services:
  - docker
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - ~/.cache
before_install:
  - rvm install 2.6.5
  - docker run -d -p 8080:8080 -e HASURA_GRAPHQL_DATABASE_URL=postgres://postgres:@localhost:5432/sandbox_test hasura/graphql-engine
  - bash bin/wait_for_port 8080
  - gem install bundler
  - bundle install
# install:
  - yarn add cypress
before_script:
  - psql -c 'create database sandbox_test;' -U postgres
  - bin/rails server &
  - bundle exec rake assets:precompile
  # - sleep 10
  - RAILS_ENV=test bundle exec rake db:schema:load
  # - RAILS_ENV=test bundle exec rake your_seed
script:
  # - $(yarn bin)/cypress run --record
  - CYPRESS_RAILS_CYPRESS_OPTS='--record' rake cypress:run
  - bundle exec rspec spec/models

