language: node_js
#node_js:
#- 10
addons:
services:
  - docker
cache:
  bundler: true
  yarn: true
  directories:
    - /home/travis/.rvm/
    - ~/.cache
before_install:
  - docker run --network="host" -e POSTGRES_HOST_AUTH_METHOD=trust -d -p 5432:5432 postgres
  - bash bin/wait_for_port 5432
  - sleep 15
  - docker logs $(docker ps | sed -n '2 p' | awk '{print $1;}')
  - psql -c 'create database sandbox_test;' -U postgres
