default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username:
  password:
  pool: 5

development:
  <<: *default
  database: sandbox_development

test: &test
  <<: *default
  database: sandbox_test

staging:
  <<: *default
  database: sandbox_staging
